### ISSUE TITLE
Understanding the data file at Setup stage

### ISSUE THREAD

**Issue by sakeogh** [LibraryCarpentry/lc-open-refine#112]
On the [Setup page](https://librarycarpentry.org/lc-open-refine/setup.html) for Open Refine I think it would be useful for the participants to see the data that they will be working with so that they understand why they are making the selections at the upload stage. So under 'Downloading the data' section, I propose adding a line at the end of the paragraph.
Following
 
> ...Make a note of the location (i.e the folder, your desktop) to which you save the file.

add the line;

> Open the data file to ensure it has downloaded correctly, and to see how the data is formatted.

This should also help ensure that the file was downloaded and will be one less thing that might go wrong at the start of the class.

**Comment by ostephens** [comment]
Thanks @sakeogh 

I think ensuring participants understand why they are making specific selections at the upload stage is definitely a good idea, but I'm not sure that adding this line to the Setup page will necessarily achieve that.

If we are going to make an addition here, I think it should be part of the episode where the upload happens rather than in setup.

In terms of making sure the file downloaded correctly - I think that's a reasonable thing to add to setup, but I'm not completely convinced it is needed.

**Comment by sakeogh** [comment]
It probably is a bit prescriptive. I could just get the class to open the file before we upload it, and flip between the CSV and TSV options on the OR. Thanks.

**Comment by libcce** [comment]
@sakeogh @ostephens did you come to a decision? Sounds like adding your example text to where the data upload happens in the lesson? If so, @sakeogh would you mind submitting a pull request by clicking on the improve this page link in the lesson episode? Thanks!!!

**Comment by sakeogh** [comment]
@ostephens, you think the step is not really necessary, and maybe it's not, it can be something instructors might naturally decide to look at or not, but doesn't need to be included. So @libcce, four months later, will I leave it and close this?

**Comment by libcce** [comment]
It has been a while @sakeogh but looks like @ostephens was in favor of updating text within the context of the episode at the upload stage? I believe you can move this to a pull request.

**Comment by jas58** [comment]
Closing, as the "going further" part of the Import episode invites playing with the settings.
