### ISSUE TITLE
Removing use of "simple" in lesson objectives

### ISSUE THREAD

**Issue by hannahcgunderman** [LibraryCarpentry/lc-open-refine#114]
Hello! As part of my checkout process, I would like to offer the following feedback and suggested change to the learning objectives to the "Faceting and Filtering" section of this lesson found here: https://librarycarpentry.org/lc-open-refine/04-faceting-and-filtering/index.html. 

In particular, the two learning objectives below: 
1. Answer simple questions about the content of a data set using Facets
2. Correct simple data problems through a facet

In my recent Carpentries instructor training, we were taught to avoid the use of the phrasing "simple" or "easy" in any aspect of the Carpentries workshops, as it may alienate folks who are new to working with the tool at hand and create an unwelcoming learning environment for them. Here, I believe we should remove the use of the word "simple" in both objectives, as it may encourage the instructor to use these terms when going through this particular lesson. Here's my two proposed changes to the phrasing: 

1. Answer questions about the content of a data set using Facets. 
2. Correct data problems through a facet. 

I appreciate your consideration of my discussion here!

**Comment by ostephens** [comment]
Thanks very much @hannahcgunderman 

I think the use of "simple" here is aimed at the questions/problems rather than suggesting the task itself is 'simple' - basically it was to indicate that the objective was only aimed at doing some basic checking/fixing.

On the otherhand, I can't see that we really lose anything by dropping the word 'simple' from these objectives - so would be happy to see a Pull Request that did this

**Comment by hannahcgunderman** [comment]
Excellent! I will initiate a Pull Request.

**Comment by ostephens** [comment]
Fixed by #116
