### ISSUE TITLE
Episode #1. Introduction to OpenRefine--add a "Basics" section 

### ISSUE THREAD

**Issue by MelissaRat** [LibraryCarpentry/lc-open-refine#124]
When I have taught OpenRefine the biggest questions I have had are about if an internet connection is needed, privacy concerns, and saving/workflow across multiple computers.  I therefore suggest adding these "basics" bullets before the discussion of why it is useful/scenarios. 

- OpenRefine is a desktop application that uses your web browser as a graphical interface.
- No internet connection is needed, and none of the data or commands you enter in OpenRefine are sent to a remote server so therefore it's good for working with sensitive data.
- You are NOT modifying original/raw data.
- Saving will happen automatically, but it's important to properly shut down OpenRefine to ensure this. (add link to install instruction which talk about shut down: https://github.com/OpenRefine/OpenRefine/wiki/Installation-Instructions) 
- Files are saved locally such that if you are working on two computers you will have to export/import files/projects.

**Comment by ameliakallaher** [comment]
I second @MelissaRat . These suggestions cover some great basics that novice users would want to know/should know. Also, when I have taught with OpenRefine in the past I would ask workshop attendees why they're interested in learning how to use OpenRefine as an initial icebreaker question but also to get at where attendees are coming from on campus or what their background interests are. I have noticed some people are interested in OpenRefine from a collaboration tool aspect. They work in a department, team, or lab with individuals of varying skill levels when it comes to technology. OpenRefine is a good "meeting in the middle" tool to them; they don't need everyone on the team to learn a programming language or how to code in order to contribute.  Perhaps consider editing the line "It is probably easiest to describe the kinds of data OpenRefine is good at working with and the sorts of problems it can help you _or a team_ solve."

**Comment by libcce** [comment]
Thanks for these suggestions @MelissaRat @ameliakallaher 😄 There are two places where we can add this information, the introduction and/or instructor notes. @MelissaRat I believe https://github.com/LibraryCarpentry/lc-open-refine/issues/16 is related as well? Something we've been meaning to get to. If one/both of you would like to create a pull request to make these changes... we'd be grateful! You can click on the improve this page link at the top of the lesson episode to submit a pull request. Once you've done that you can link to the pull request here so that the issue and pull request are linked. Thanks a million!

**Comment by jreeveseyre** [comment]
@libcce I'd be happy to have a go at creating a pull request to make the above changes if @MelissaRat and/or @ameliakallaher haven't done so already. I didn't see anything in the list of pull requests, but I wanted to double-check!

**Comment by libcce** [comment]
Thanks @jreeveseyre I know we've had some issues that haven't been linked to PRs, but I'm sure you will double check. Thanks a million for creating the PRs!

**Comment by MelissaRat** [comment]
@jreeveseyre I haven't yet so thanks!

**Comment by ostephens** [comment]
Closed by #141
