### ISSUE TITLE
Episode 4: Faceting and filtering- suggested revisions to intro to define filters and remove demotivating term

### ISSUE THREAD

**Issue by rareleah** [LibraryCarpentry/lc-open-refine#137]
As part of the instructor training checkout process I am submitting the following suggested revisions to the [Facets and Filtering episode ](https://librarycarpentry.org/lc-open-refine/04-faceting-and-filtering/index.html)of the Library Carpentry OpenRefine lesson.

I've reviewed and taught this lesson several times now and tend to provide a more explicit definition for "filters" that I find useful and others may too. I am also suggesting some additional language that connects to the objectives for this episode as well as the removal of "simplest" and "simply" because of the demotivational potential and because it's repetitive. 

Current text: 
Facets are one of the most useful features of OpenRefine and can help in both getting an overview of the data and to improve the consistency of the data. A ‘Facet’ groups all the values that appear in a column, and then allows you to filter the data by these values and edit values across many records at the same time. The simplest type of Facet is called a ‘Text facet’. This simply groups all the text values in a column and lists each value with the number of records it appears in. 

Suggested revisions: (bolded)
Facets are one of the most useful features of OpenRefine and **can help provide an overview of the data, answer questions with the data, and allow you to correct inconsistencies in the data.**  **Facets and filters work together: A ‘Facet’ groups all the values that appear in a column and a filter allows you to limit (or filter) your view to a subset of the data by these faceted values.** **Facets and filters also allow you to review and edit values across many records at the same time, thus improving the consistency of the data.****The most straightforward type of Facet is called a ‘Text facet’. A text facet groups** all the text values in a column and lists each value with the number of records it appears in. 

My suggestions might make the intro too long and possibly cause cognitive overload though. In any case, thank you for considering any of these suggested edits.

**Comment by sheraaronhurt** [comment]
Comment on behalf of Instructor Trainee for Checkout: 

I want to make a comment that I agree with rareleah to modify language in the lesson so it does not have demotivating language like "simply". Their revision is also one that I endorse.


One suggestion I have for episode 4 is to remove reference to regular expressions in the filters section since it is out of scope with this lesson and I learner might not know what it is yet. https://librarycarpentry.org/lc-open-refine/04-faceting-and-filtering/index.html

**Comment by wjohnsonfreeman** [comment]
@rareleah 

I this is a great suggestion to update the descriptions of faceting and filtering because the current descriptions are a little confusing.

However, I suggest that the description for the 'Text Filter' be updated. The description could be a little more clear on what makes it different from facets. The 'Text Filter' is unique because it uses a string, entered by the user, to filter the data, while facets are generated by OpenRefine based on the content of the column. 

Here is the introduction/description of the 'Text Filter' with my suggestions in bold:

_Filters_
As well as using Facets to filter the data displayed in OpenRefine you can also apply ‘Text Filters’ which **look** for a particular piece of text appearing in a column **based on a unique text string, like a 'find' feature**. Text filters are applied by clicking the drop down menu at the top of the column you want to apply the filter to and choosing ‘Text filter’.

This is a part of my Instructor Training Checkout Process.

**Comment by ostephens** [comment]
Thanks to all who have commented on this issue. If a pull request were made to make some of these suggested changes then that would really help us move this issue forward. It looks like there is general agreement about the changes so a pull request is what's needed next. See the [Contributing](https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/CONTRIBUTING.md) instructions for more details on making a pull request.

I'm happy to give advice and support for anyone interested in getting a pull request to get this changed

**Comment by jas58** [comment]
I can no longer locate "simply" or "simplest" on the lesson today.
I think I see the suggested edit in the lesson.
