### ISSUE TITLE
Suggested revisions to Transformations - Handling Arrays 

### ISSUE THREAD

**Issue by abigailsparling** [LibraryCarpentry/lc-open-refine#142]
Having taught this workshop twice recently I had the following feedback:

[Transformations - Handling Arrays](https://librarycarpentry.org/lc-open-refine/11-using-arrays-transformations/index.html) 
To really demonstrate the content in this lesson and allow students to follow along I ended up editing a cell and adding the example array. This way I could demonstrate the GREL and the results in the transformation window. I find this section is easiest for students to understand if they're able to see the results of the GREL on the data as each piece of the expression is added. In an ideal world there would be a column we could act on in this way to demonstrate the GREL functions outlined in this lesson, and so students could follow along if they wanted.

**Comment by ostephens** [comment]
Thanks very much @abigailsparling. Would you be willing to split these into two issues so we can discuss and fix separately?

**Comment by ostephens** [comment]
Thanks for raising this @abigailsparling - I completely agree we could improve this part of the lesson.

I'd suggest that we could use the Subject column for this example, and as well/instead of `sort()` which is currently the example used for manipulating the array, `uniques()` might be a better example, as there are actually duplicates in some cells, so we get to give a better real-life example

**Comment by jas58** [comment]
Yes, uniques() sounds like a good option.

**Comment by jas58** [comment]
Is this asking for an edit to episode 11 line 32? Or after line 51 and before the checklist? Or at the beginning of these (row 24)?
Is it an addition of: 
"Add '''unique'''
code
value.unique()
to open a column on the left where you can observe the cells that will be effected and the potential effect. Remember the undo option above the left column or revert to a step before unique (second tab in left column's header)."

**Comment by ostephens** [comment]
I think it needs slightly more extensive changes to move from the "days of the week" example to basing it on an example from the data used in the exercises. So I'd suggest that we consider:
* Changing from days of the week to a list of subject headings, separated by a pipe character | (as in the data)
  * For example:
  * > crystal structure|clozapinium|crystal structure|molecular configuration|hydrogen bonding|supramolecular assembly|Chemistry|QD1-999
  * This subject string can be found for the title "The crystal structures of three clozapinium salts: different molecular configurations, and supramolecular assembly in one, two and three dimensions" in the original project - we can mention this in the lesson or instructor notes?
* Use `value.split("|")` as the expression to create the array in each case
* Replacing the example of using 'sort()' on the array with 'uniques()'
  * `value.split("|").uniques()` will give `["crystal structure","clozapinium","molecular configuration","hydrogen bonding","supramolecular assembly","Chemistry","QD1-999"]` (the extra 'crystal structure' has been removed)
* Update the rest of the text to be with the new example (e.g. use `value.split("|")[0]` to get "crystal structure" instead of the current "Monday" example
* Use `value.split("|").uniques().join("|")` for recreating the list of subjects

How do that sound?

**Comment by jas58** [comment]
I gave it a try.  As this is not something I do regularly, or ever before, PR unkown number (I see 'patch 4)' needs revisions.

**Comment by ostephens** [comment]
Thanks for starting this @jas58. I've opened PR #258 based on the branch you created (Patch 4). I've marked as a draft for now as agree it needs some revisions before it's ready to be merged. I'll make some additions to the branch when I have some time - hopefully in the next day or two

**Comment by jas58** [comment]
For 11/18, I'm still unsure where to look for these comments or revisions.  Item 4?

**Comment by ostephens** [comment]
Sorry - I've completely failed to add my comments - I'll try to get some thoughts together before we talk on the 18th Nov 22

**Comment by jas58** [comment]
@abigailsparling Hi, again, Abigail!  Happy New Year!  Owen and I have been trying to work on these suggestions.  Would you have a moment in the next 4 weeks to look them over?  I'll mention you in the branch, too.  Thank you, Jennifer Stubbs

**Comment by ostephens** [comment]
Closed by #258
