### ISSUE TITLE
Open Refine Setup page only references Oracle version of Java

### ISSUE THREAD

**Issue by dipietroc** [LibraryCarpentry/lc-open-refine#151]
Proposing update to the Open Refine setup page:

[https://librarycarpentry.org/lc-open-refine/setup.html](url)

The information listed for the Open Refine setup mentions Java as a requirement to run. However, I also know that Java has more recently moved to a paid license model. If an organization did not subscribe to the paid Java license, and, depending on whether or not a user is utilizing a workplace computer to run OpenRefine, this may prevent a user from downloading and running the Oracle version of Java on their PC.

I propose adding the OpenRefine GitHub page link below to the setup instructions. The link guides users on how to run OpenRefine with an OpenSource version of Java, called OpenJDK.

[https://github.com/OpenRefine/OpenRefine/wiki/Setup-JAVA](url)

Suggestion for updated text:

OpenRefine is a Java application, and you need to have a ‘Java Runtime Environment’ (JRE) installed on your computer to run OpenRefine. If you don’t already have one installed then you can download and install from http://java.com by going to the site and clicking “Free Java Download”.

If you are unable to download and run the Oracle version of Java at your institution, you may alternatively use OpenJDK instead, by following the instructions contained in the following link:

[https://github.com/OpenRefine/OpenRefine/wiki/Setup-JAVA](url)

**Comment by evanwill** [comment]
I recently updated [my own Refine workshop install](https://evanwill.github.io/openrefine-b/content/2-start.html) and removed mention of installing Java. However, as the setup is now, it might be good to be more explicit about the correct package to use, since https://openrefine.org/download.html provides: 

- "Windows kit" (*requires separate Java installed*)
- "Windows kit with embedded Java" (includes OpenJDK in the package, no need to install Java)
- "Mac kit" (includes OpenJDK in package, no need to install Java)

Also worth clarifying, as @dipietroc mentions, the new Oracle Java license (updated in 2019) redefined "personal use", so most librarian's work probably doesn't fit--so we would be better to suggest using OpenJDK if people want to use the traditional Java kit. Since this applies only to Windows (Mac kit has only one option that includes Java, Linux kit requires Java, but Linux users will install openjdk by default from distro repositories)--I wrote this guide: https://evanwill.github.io/openrefine-b/content/win-java.html

I could create PR if this makes sense.

**Comment by ostephens** [comment]
@evanwill if you were willing to create a PR I'd be very happy to review it and hopefully we can get this updated. Thanks

**Comment by evanwill** [comment]
@ostephens could you look at PR #178 first, which just updates all the links from old Wiki to the new User Manual? 
It would be a bit easier to update the setup page with that in place first.

**Comment by ostephens** [comment]
@evanwill #178 now merged. Thanks so much for this

**Comment by evanwill** [comment]
@ostephens great! 
I opened PR #179 with a try at this revision.

**Comment by ostephens** [comment]
Closed by #179
