### ISSUE TITLE
When to use OpenRefine

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#16]
See https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/86 for when to use OR and when not to

**Comment by ppival** [comment]
It is ok to close this "issue"? It's much more a discussion, and seems to be "resolved" over at the depreciated link... @weaverbel @ostephens @ccronje

**Comment by libcce** [comment]
Hi @ppival looks like we lost track of the original suggestion from the deprecated issue:

As part of the introduction about the uses of OpenRefine, it might be useful also discuss its limitations and when it should be used independently versus in concert with other tools (regex, Python, etc).

I'm tagging this as a nice first issue for the upcoming sprint.

**Comment by jyssy** [comment]
Are we suggesting we need a new 'when to use open-refine' lesson? One could perhaps use some content from that closed/deprecated thread to start populating the lesson, maybe???  I just want to make sure I understand what is expected from this particular issue. thank you

**Comment by ostephens** [comment]
I think suggestion was that it could be part of the first episode "Introduction". Possibly some of the content from that closed/deprecated thread could be used as part of that

**Comment by libcce** [comment]
@jyssy @ostephens I think that is correct. This would be a very brief section on the limitations of OpenRefine based on some of the ideas in the deprecated issue. As mentioned in that deprecated issue thread, a programming language like Python is sometimes better for more advanced programmatic tasks or that a visualization tool is sometimes more appropriate than OpenRefine (it is more of a faceted browsing tool).

**Comment by emcaulay** [comment]
I think this is a good suggestion, but it has laid dormant for a while. I recommend this issue be closed so that the lesson maintenance and issues can focus on changes that are actively being suggested. 

If one of the maintainers on this lesson is animated to add this type of content, as an instructor of this material, I suggest it be added to the end of the lesson in the final episode. Because at the start of the lesson I want to stay focused on the positive. I want to talk about why the tool is worth learning and using. At the end, and if I have time, then I can talk about the bigger picture. 

Lastly, I think by pushing this "bigger picture" information to a later episode in the lesson, our lesson will continue to align with the pedagogy of "teach useful things first" from the instructor training.

**Comment by ostephens** [comment]
Agreed @emcaulay. Any work to add this kind of context to the lesson will be very welcome, but lets close this very long standing issue as it has not been picked up in 3+ years
