### ISSUE TITLE
Lesson Contribution - Adjustments after Updates to OpenRefine

### ISSUE THREAD

**Issue by Talishask** [LibraryCarpentry/lc-open-refine#169]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
---

With the update to OpenRefine 3.4, some of the examples and exercises in the "Introduction to Transformations" (https://librarycarpentry.org/lc-open-refine/07-introduction-to-transformations/index.html) aren't relevant, namely trimming whitespace. I think it would be confusing to students to have to turn on this default and turn it back on, but it may be worth mentioning to students in the "Importing Data" that this is the kind of normalization or clean up that OpenRefine does by default and give some examples of data that would have that issue and why it matters. If another example of a simple transformation is needed, perhaps adding a step demonstrating using the "To Number" transformation, since this would resonate with individuals who use Excel frequently.

**Comment by ostephens** [comment]
Thanks @Talishask this is very helpful.

For further clarification:

From OpenRefine 3.4 there is an option to trim trailing whitespace from fields in a csv/tsv on import, and this option is turned on by default (for full details see the change to OpenRefine https://github.com/OpenRefine/OpenRefine/pull/2408)

This means that on import, the issue that is currently identified and fixed in Episode 7 won't exists unless students are deliberately told to turn off the default option when they initially import the data (in Episode 2). I agree with the comment above - telling students to turn off this option to create the problem doesn't make much sense.

I agree we need to change the simple transformation used in Episode 7. The thing about the "trim whitespace" example is that it was practical (fixed a very common problem) and was easily applicable to the data set used for the lesson - I'm not sure 'toNumber()' meets this requirement (there is no obvious numerical data for us to transform in the data set, and toNumber() potentially has more complex outcomes to explain to the students which lead to a more complicated explanation at this stage)

So I think we need to:

- [ ] Update Episode 2 to mention this option explicitly and update the screenshot with the 3.4.x (3.4.1 is the current version) import screen
- [ ] Identify an alternative simple, but useful, "common transformation" that can be used with the data, if necessary introducing a new common issue to the data that has been imported

My initial thought on the "common transformation" is that we could introduce a double space into the publisher data that needs to be resolved using the "Collapse Consecutive Whitespace" transformation - this keeps it very similar to the current example and demonstrates quite a similar type of data issue.

I'd be interested to know what others think - but obviously it would be good to get this fixed quickly

**Comment by ostephens** [comment]
@partiecolored @ppival @kristindawn what do you think?

**Comment by partiecolored** [comment]
Thanks @Talishask and @ostephens. I think your suggestions make sense, Owen.

**Comment by ostephens** [comment]
@partiecolored I've done a PR with these changes - if you can review when you have a chance that would be great. Thanks in advance 🙏
