### ISSUE TITLE
Advanced lesson?

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#20]
https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/65

**Comment by ppival** [comment]
Can this be closed as an issue? @weaverbel @ostephens @ccronje

**Comment by libcce** [comment]
I pulled the ideas from the deprecated issue thread here:

Proposed Advanced OpenRefine syllabus
What should be covered? Proposals here:
1) Advanced GREL examples
2) Build on examples and topics in the advanced episode http://data-lessons.github.io/library-openrefine/05-advance-functions/ 
3) More API examples using GREL to pick apart the XML/JSON 
4) Named entity extraction
5) Using Jython to do things that are hard/impossible in GREL

@ostephens @ccronje @ppival @partiecolored @pitviper6 @kristindawn what do you think?

- Per 1, I believe https://github.com/LibraryCarpentry/lc-open-refine/issues/17 will respond to it
- Per 2, we can create a 'good first issue' asking if anything else should be added to the advanced episode
- For 3, I think we can drop it
- For 4, would it be another reconciliation service we can point to in https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html
- Per 5, this might be too advanced, can we point to a blog post/tutorial that we can reference somewhere in the lesson?

**Comment by ostephens** [comment]
This is a very long standing issue now. I still believe that the 5 things itemised by @libcce above would be good additions - in fact I did exactly that in a non-carpentry lesson I teach:

* [Variable, regular expressions, NER, JSON](https://docs.google.com/document/d/1qJ75QX12R3RTAQCr5lQQCy7aG2Xfx-Htr76vmcYC724/edit?usp=sharing)
* [Reconciliation and Cross](https://docs.google.com/document/d/1eVtvnMOgTwIoHAqRMvtiED8CtLeBLUcNgwtchUbzIa4/edit?usp=sharing)
* [More regular expressions, Jython](https://docs.google.com/document/d/1eVtvnMOgTwIoHAqRMvtiED8CtLeBLUcNgwtchUbzIa4/edit?usp=sharing)

In terms of Library Carpentry we could either add extra episodes to this lesson, or create a separate lesson for these topics.  If the former we'd need some way to make the expected "core lesson" clear because we can't expect to add any more content to the existing lesson without it being too long to teach in 3hrs

**Comment by emcaulay** [comment]
I recommend that this issue be closed. This issue if proposing a new lesson, and I think it would be great. However, that isn't relevant to maintaining the existing episode.

**Comment by ostephens** [comment]
Agreed - I'm closing this issue. If anyone wishes to work on an advanced open refine lesson, or make proposals of changes to this lesson to incorporate new / different topics, then that would still all be very welcome, but specific discussions or issues can be opened for any such work
