### ISSUE TITLE
Order of topics

### ISSUE THREAD

**Issue by mfeustle** [LibraryCarpentry/lc-open-refine#205]
A case could be made for re-ordering the presentation of topics in the OpenRefine lesson for a better match with the Carpentries' interest in prioritizing the most useful / most used features. 

One possible configuration here would be to begin with clearing leading/trailing and consecutive whitespace, followed by a demonstration of the Undo/Redo (or rather step forward/backward) function, followed by facets and clustering. "Layout of OpenRefine, Rows vs Records" deals with more advanced concepts, and could flow better after "Working with columns and sorting."

**Comment by ostephens** [comment]
I'm not against re-ordering but it feels like this could be a reasonable amount of work without necessarily a huge amount of gain. I tend to agree that Undo/Redo comes late in the lesson, but it's also more interesting to show it once people have made a reasonable number of changes to the project.

I think it's important to tackle Records before Faceting and Clustering, because it's important to have unique value per cell for Faceting and Clustering to be effective - and talking about splitting the multi-valued cells and the way OpenRefine handles this as "Records" allows this to be illustrated and is one of the more unusual features of OpenRefine that separate it from other tools (at least in my opinion)

If there is some clear indication that the current order is leading participants to switch off or lose interest early in the lesson then I'd definitely agree the order should be looked at. I've not experienced this when teaching the lesson and not seen this feedback from others, but if your experience is different then I'm definitely open to reviewing.
