### ISSUE TITLE
Is toTitlecase a good "data cleaning" example?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-open-refine#243]
After [the `Put titles into Title Case` exercise](https://github.com/LibraryCarpentry/lc-open-refine/blob/v2019.06.1/_episodes/08-writing-transformations.md#put-titles-into-title-case):

- some of the example data's inaccuracies become more visible :-)
- But also the [incorrect capitalisation](https://en.wikipedia.org/wiki/Binomial_nomenclature) of `Genus species` :-(

![image](https://user-images.githubusercontent.com/9948149/187269595-502fb71c-6fd1-4d3d-b840-aae313b01993.png)

Might it be better to replace that example with something _less double-edged_?

For example with a GREL equivalent to the `Collapse consecutive whitespace` exercise from [07-introduction-to-transformations](https://github.com/LibraryCarpentry/lc-open-refine/blob/v2019.06.1/_episodes/07-introduction-to-transformations.md#correct-publisher-data)?

This would necessitate:

- swapping [09-undo-and-redo](https://github.com/LibraryCarpentry/lc-open-refine/blob/v2019.06.1/_episodes/09-undo-and-redo.md) with [08-writing-transformations](https://github.com/LibraryCarpentry/lc-open-refine/blob/v2019.06.1/_episodes/08-writing-transformations.md)
- rewriting the former to _undo_ the `Collapse consecutive whitespace`
   - copy that GREL expression `value.replace(/[\p{Zs}\s]+/,' ')` and explaining it a bit.
- rewriting the latter to do the action again the GREL way.

---

Related to #242

**Comment by jas58** [comment]
Thank you for bringing up this concern.
May I ask if you have specific transformations in mind?  The goal of this lesson is to gently introduce complete beginners to simple, clear, and obvious mistakes in a short amount of time.  Could you generate a list of the double-edged transformations to avoid? As well as list (maybe 3?) that remain simply, clear, and obvious?

On another hand, might this become an instructor note and warning that transformations are performed across everything and not always reversible?  For example, acronyms like DARE become Dare.  Then this might become a reflective exercise for learners to propose potential risks or problems to anticipate.

We look forward to this discussion.

**Comment by katrinleinweber** [comment]
Hi @jas58 👋 I agree that this issue could also be resolved with "an instructor note and warning".

About your 1st paragraph: It sounds like my screenshot might not be loading for you? It contains a few orange-marked examples of the problems highighted by using `Put titles into Title Case` with the doaj data.

> … you have specific transformations in mind?

Only `Put titles into Title Case`, and `Collapse consecutive whitespace` as its alternative.

> The goal of this lesson is to gently introduce complete beginners to simple, clear, and obvious mistakes in a short amount of time.

If seeing those orange-marked typos is exactly the point of the lesson, this issue is indeed moot.

**Comment by ostephens** [comment]
@katrinleinweber 

> If seeing those orange-marked typos is exactly the point of the lesson, this issue is indeed moot.
No that's not the point - the point is not about the data but about writing a transformation using GREL.

The reason for originally choosing `toTitlecase()` here is because it's extremely simple and has a very clear outcome - that is it's very easy for the learner to :

* write correctly
* understand what it's supposed to do
* see that it is doing exactly what it's supposed to
* see the transformation applies to all the rows currently selected

I don't have an issue with replacing with a different example that also meets these criteria, but I don't think the `Collapse consecutive whitespace` achieves this - it's a complex expression that requires the learner to understand regular expressions (and not a simple one) and is much harder to spot the result, and of course while it applies to all the rows selected, it will only change ones where there are consecutive whitespaces.

I think if we are going to change the example here it has to be one that fulfils the majority of the criteria above. If we can come up with a more meaningful example I'm very happy.

**Comment by katrinleinweber** [comment]
> `toTitlecase()` has all kinds of issues as a data cleaning step here - and when I teach OpenRefine I always highlight this … just because you can do something doesn't necessarily mean you should do it.

I apparently overlooked that meta-learning goal when I created this issue 😊

**Comment by ostephens** [comment]
> I apparently overlooked that meta-learning goal when I created this issue 😊
I think this is a good point - if we are going to leave this example as is, perhaps we should add something more explicit (rather than just an instructor note) and add something to the key points and/or objectives to highlight it?
