### ISSUE TITLE
Improving Column Split exercise for OpenRefine

### ISSUE THREAD

**Issue by mhayslett** [LibraryCarpentry/lc-open-refine#34]
In preparing for the second day of instructor training, I went through the OpenRefine lesson on faceting using the portal_rodents dataset and found two places where the lesson could maybe improve:

1.	Where you split the Scientific Name column on a space, I got confused with the instructions initially and (not thinking) thought I was supposed add a space *in addition to the comma* (it was 9:30 pm, my only excuse).  I figured it out when it didn’t work (had to use the Undo/Redo screen earlier than the lesson called for) but when I taught it to my partner the next day, that experience made me emphasize that one could split the column on *any* character, that the default was a comma but you could change that to a space.  
2.	Later in the lesson when it called for trying to rename the column, the note says that students won't succeed and prompts them to think about why.  I actually did succeed in renaming mine *because I capitalized the word Species* instead of leaving it lowercase.  So the follow up discussion might benefit from asking, not “why didn’t that work”, but instead, “Did you get that to work?  Can you think of a reason why it might work versus not?”

**Comment by ostephens** [comment]
@mhayslett thanks for these suggestions. Are you able to go ahead and suggest some edits through a pull request? 

If not, that's no problem - if you layout clearly the changes you think should be made then someone else could pick it up and make a pull request for it (you've already done this for 2 I think, but maybe for 1 suggest what change you think needs making)

**Comment by mhayslett** [comment]
I don't have much experience with pulls but I can try--it'll just take longer b/c I have to carve out the time.  But it's a good small project on which to re-acquaint myself with it (got instruction last October); will try to do by end of next week but after 3/1 it's open season.  For 1, it's just to add a note to learners that the obvious split character in this case is a space but the character could be anything (even [maybe] a word?).

**Comment by ostephens** [comment]
@mhayslett I think this isn't really urgent so happy to leave you to fix if you can. If you decide you don't have time just post a note here and someone else can pick it up.

If you hit any issues making the changes & PR feel free ask on here and someone will try to help

**Comment by mhayslett** [comment]
I don't have much experience with pulls but I can try--it'll just take longer b/c I have to carve out the time.  But it's a good small project on which to re-acquaint myself with it (got instruction last October); will try to do by end of next week but after 3/1 it's open season.  For 1, it's just to add a note to learners that the obvious split character in this case is a space but the character could be anything (even [maybe] a word?).

**Comment by mhayslett** [comment]
I think I did it!  I just put in the pull request to submit the changes.

**Comment by ostephens** [comment]
Hey @mhayslett - that's brilliant - unfortunately a couple of issues (one is my fault, so apologies):

Firstly (and my fault for not spotting this early) the problem you've identified is with the Data Carpentry Ecology OpenRefine lesson, not the library carpentry lesson - so this issue should have been reported to https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues rather than here - I should have known this from the report, but I obviously didn't read it carefully enough.

Happily though this won't affect your pull request because I can see that https://github.com/mhayslett/OpenRefine-ecology-lesson is forked from the right DataCarpentry lesson, so any PR will go to the right repository.

The second issue is that you've made the change in your repository, but you haven't made a pull request yet - to do this use the "New Pull Request" option from your repository https://github.com/mhayslett/OpenRefine-ecology-lesson and this will create a PR against https://github.com/datacarpentry/OpenRefine-ecology-lesson which hopefully one of the maintainers of that repository will review for you

Best wishes

Owen
