### ISSUE TITLE
Include language about how OpenRefine opens on different Operating Systems?

### ISSUE THREAD

**Issue by tishamentnech** [LibraryCarpentry/lc-open-refine#73]
Could there be language included about how the start up process of launching OpenRefine will open terminal window on PCs but not in Macs? (I've not seen OpenRefine launched on a linux machine know if a terminal window occurs)

**Comment by libcce** [comment]
@tishamentnech do you see that being added to the setup page https://librarycarpentry.org/lc-open-refine/setup.html ?

**Comment by libcce** [comment]
Thanks @tishamentnech. I forgot to ask you, and how would you phrase the message?

**Comment by libcce** [comment]
@tishamentnech on the setup page, would you recommend language about the terminal window on PCs here:

"The interface to OpenRefine is accessed via a web browser. When you run Refine normally this should open a window in your default web browser pointing at the address http://127.0.0.1:3333. If this doesn’t happen automatically you can open a web browser and type in this address."

**Comment by ostephens** [comment]
The way we currently have this structured, I think Setup.md is the right place for this information - since it already contains information on how to run OpenRefine in the different operating systems it also seems like the right place to have the information on how the s/w runs slightly differently on each platform?

I think the alternative would be to bring all this information into episode 2 - although I feel it clutters up the lesson and it isn't my first choice, given we've had a number of comments around this it seems worth considering.

**Comment by tishamentnech** [comment]
@libcce I think where you're recommending on the setup page would be sufficient. I agree with @ostephens that on episode 2 would add clutter to that portion.

For language, I think something along the lines of when launching OpenRefine on windows machines you will see a terminal window, make sure to keep that open since that is what is running the program.

**Comment by libcce** [comment]
Thanks @tishamentnech ! Hopefully this works https://github.com/LibraryCarpentry/lc-open-refine/pull/78 if @ostephens has additional advice.

**Comment by ostephens** [comment]
Thanks both - that looks great. Merged!
